PhotoAlbum/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhotoAlbum.Data;
using PhotoAlbum.Models;
using System.Diagnostics;

namespace PhotoAlbum.Controllers
{
    // restricted access
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PhotoAlbumContext _context;
       
        // My Home Controller
        public HomeController(ILogger<HomeController> logger, PhotoAlbumContext context)
        {
            _logger = logger;
            _context = context;
        }
                
        // GET: Photos
        public async Task<IActionResult> Index()
        {
            // Get all photos
            var photos = await _context.Photo
                .OrderByDescending(m => m.PublishDate)
                .ToListAsync();

            return View(photos);
        }

        // GET: Photos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // URL is missing the 3rd parameter ID
            if (id == null)
            {
                return NotFound();
            }

            // Get record where PK = id
            var photo = await _context.Photo.FirstOrDefaultAsync(m => m.PhotoId == id);

            // Record not found in the database
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }
    }
}

PhotoAlbum/Controllers/PhotosController.cs
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PhotoAlbum.Data;
using PhotoAlbum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoAlbum.Controllers
{
    // restricted access
    [Authorize]
    public class PhotosController : Controller
    {
        private readonly PhotoAlbumContext _context;
        private readonly IConfiguration _configuration;
        private readonly BlobContainerClient _containerClient;

        public PhotosController(PhotoAlbumContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;

            var connectionString = _configuration["AzureStorage"];
            var containerName = "photo-album-uploads";
            _containerClient = new BlobContainerClient(connectionString, containerName);
        }        

        // GET: Photos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhotoId,Title,Description,FormFile")] Photo photo)
        {
            // Set the publish date
            photo.PublishDate = DateTime.Now;

            // Validate form input
            if (ModelState.IsValid)
            {
                //
                // Step 1: save the file (optionally)
                //
                if (photo.FormFile != null)
                {
                    //
                    // Upload file to Azure Blob Storage
                    //

                    var fileUpload = photo.FormFile;

                    // the name of the file to save in Azure (guid + fileName)
                    string blobName = Guid.NewGuid().ToString() + "_" + fileUpload.FileName;

                    var blobClient = _containerClient.GetBlobClient(blobName);

                    using (var stream = fileUpload.OpenReadStream())
                    {
                        await blobClient.UploadAsync(stream, new BlobHttpHeaders { ContentType = fileUpload.ContentType });
                    }

                    // Get the URL of the blob file
                    photo.Filename = blobClient.Uri.ToString();
                }

                //
                // Step 2: save the record in db
                //
                _context.Add(photo);

                await _context.SaveChangesAsync();
                
                return RedirectToAction("Index", "Home");
            }

            return View(photo);
        }

        // GET: Photos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photo.FindAsync(id);

            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhotoId,Title,Description,Filename,PublishDate,FormFile")] Photo photo)
        {
            if (id != photo.PhotoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //
                // Step 1: save the new file (optionally)
                //
                if(photo.FormFile != null)
                {
                    // 1. Change the filename in photo.Filename

                    // 2. Save the new file

                    // 3. Delete the old file
                }

                //
                // Step 2: save the record
                //

                try
                {
                    _context.Update(photo);
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoExists(photo.PhotoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Index", "Home");
            }

            return View(photo);
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photo
                .FirstOrDefaultAsync(m => m.PhotoId == id);

            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var photo = await _context.Photo.FindAsync(id);

            if (photo != null)
            {
                _context.Photo.Remove(photo);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }

        private bool PhotoExists(int id)
        {
            return _context.Photo.Any(e => e.PhotoId == id);
        }
    }
}

PhotoAlbum/Views/Home/Details.cshtml
@model PhotoAlbum.Models.Photo

@{
    ViewData["Title"] = "Details";
}

<h1>Photo Details</h1>

<div>
    <hr />

    <div class="w-50">
        <img src="@Model.Filename" alt="@Model.Title" class="img-fluid" />
    </div>

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Home" asp-action="Edit" asp-route-id="@Model?.PhotoId">Edit</a> |
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

PhotoAlbum/Views/Home/Index.cshtml
@model IEnumerable<PhotoAlbum.Models.Photo>

@{
    ViewData["Title"] = "Index";
}

<h1>All Photos</h1>

<p>
    <a asp-controller="Photos" asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <th>
                <img src="@item.Filename" alt="@item.Title" class="thumbnail" />
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @* @Html.DisplayFor(modelItem => item.PublishDate) *@
                @item.PublishDate.ToString("MMM dd, yyyy")
            </td>
            <td>
                <a asp-controller="Photos" asp-action="Edit" asp-route-id="@item.PhotoId">Edit</a> |
                <a asp-controller="Home" asp-action="Details" asp-route-id="@item.PhotoId">Details</a> |
                <a asp-controller="Photos" asp-action="Delete" asp-route-id="@item.PhotoId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>